# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-14 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_abilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='cooldown',
            field=models.CharField(max_length=64),
        ),
    ]
