# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_abilities', '0003_ability_is_from_talent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='spell_immunity_detail',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='ability',
            name='spell_immunity_int',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ability',
            name='cooldown',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
