# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_abilities', '0005_ability_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='is_from_aghanims',
            field=models.BooleanField(default=False),
        ),
    ]
