# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-03 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero_abilities', '0006_ability_is_from_aghanims'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ability',
            old_name='spell_immunity_int',
            new_name='spell_immunity',
        ),
    ]
