# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 18:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvantagesUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_started', models.DateTimeField(default=datetime.datetime.now, unique=True)),
                ('update_finished', models.DateTimeField(default=None, null=True, unique=True)),
            ],
        ),
    ]
