# Generated by Django 2.0.2 on 2018-02-03 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
