# Generated by Django 2.0.2 on 2018-02-03 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_auto_20180203_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponderUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responder', models.CharField(db_index=True, max_length=32)),
                ('total_uses', models.IntegerField(default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='advantagesupdate',
            name='update_started',
            field=models.DateTimeField(default=django.utils.timezone.now, unique=True),
        ),
    ]
