hero_aliases = {
    'abaddon': ['abadan'],
    'ancient apparition': ['aa', 'ai'],
    'anti-mage': ['am', 'anti mage'],
    'arc warden': ['walking'],
    'axe': ['tax'],
    'bane': ['spain', 'bayne', 'pane'],
    'batrider': ['bat rider'],
    'beastmaster': ['beast master'],
    'bloodseeker': ['blood seeker'],
    'brewmaster': ['brew master'],
    'bristleback': ['bristol', 'bristle'],
    'broodmother': ['brood'],
    'centaur warrunner': ['centaur'],
    'chaos knight': ['ck'],
    'chen': ['chan', 'shen'],
    'clockwerk': ['clockwork', 'clock'],
    'clinkz': ['clicks', 'clinks'],
    'crystal maiden': ['cm', 'maiden'],
    'dark seer': ['akira'],
    'dark willow': ['dark will', 'dog will', 'dark with', 'dog with', 'stock will', 'stock with'],
    'disruptor': ['disrupter'],
    'dragon knight': ['dragonite', 'on night', 'dragon bite', 'dragonette'],
    'drow ranger': ['drow', 'drought', 'drawer'],
    'earthshaker': ['shaker'],
    'ember spirit': ['ember', 'mbna'],
    'faceless void': ['faceless', 'void', 'face less void'],
    'gyrocopter': ['gyro', 'giro'],
    'huskar': ['tasker', 'oscar'],
    'invoker': ['in walker', 'in boca'],
    'juggernaut': ['jug', 'dragonaut'],
    'keeper of the light': ['keeper'],
    'kunkka': ['conker', 'conquer', 'commander'],
    'legion commander': ['legion'],
    'leshrac': ['track', 'electric', 'lash rack'],
    'lifestealer': ['life stealer'],
    'lina': ['lena'],
    'lone druid': ['sloane', 'lounge'],
    'lycan': ['i can', 'lichen', 'lucian'],
    'meepo': ['me po', 'mitoo'],
    'mirana': ['marana'],
    'naga siren': ['naga', 'siren'],
    "nature's prophet": ['furion', 'nature'],
    'necrophos': ['necro'],
    'night stalker': ['nightstalker'],
    'nyx assassin': ['nyx', 'mix'],
    'ogre magi': ['ogre', 'over major', 'ogre magor', 'over magi'],
    'omniknight': ['the light', 'opening', 'nonna night', 'omni', 'omni knight', 'me night', 'omni night'],
    'outworld devourer': ['out world', 'od', 'outworld', 'audi'],
    'pangolier': ['pango', 'spangly', 'panggang', 'pangolin', 'pangalan'],
    'phantom assassin': ['pa'],
    'pudge': ['patch', 'purge', 'punch', 'porridge', 'fudge'],
    'phantom lancer': ['pl'],
    'puck': ['park', 'pack'],
    'pugna': ['partner', 'pubmed'],
    'queen of pain': ['qop', 'co-op', 'qwop', 'queen of time'],
    'razor': ['razer', 'reza'],
    'riki': ['rikke'],
    'rubick': ['rubik'],
    'sand king': ['sans king', 'and king', 'sand can', 'san king'],
    'shadow fiend': ['sf'],
    'slardar': ['slider', 'louder', 'cider'],
    'storm spirit': ['storm'],
    'skywrath mage': ['skywrath'],
    'slark': ['rock', 'lark', 'luck'],
    'spectre': ['inspector'],
    'sven': ['stem', 'spam', 'spend', 'stan', 'spain', 'spin'],
    'techies': ['turkeys', 'chucky'],
    'templar assassin': ['ta'],
    'terrorblade': ['terror blade', 'terra blade', 'tb'],
    'tidehunter': ['tide hunter', 'tide', 'tired'],
    'timbersaw': ['imbecile', 'timber'],
    'treant protector': ['treant'],
    'troll warlord': ['troll'],
    'tusk': ['task'],
    'underlord': ['under lord'],
    'undying': ['and dying'],
    'ursa': ['the sun', 'airsoft', 'earth that', 'asa', "earth's uh"],
    'vengeful spirit': ['venge'],
    'venomancer': ['vino', 'veno', 'villa monster'],
    'visage': ['visit', 'research'],
    'warlock': ['war lock'],
    'witch doctor': ['which doctor', 'doctor'],
    'windranger': ['wind ranger', 'lyralei'],
    'wraith king': ['racecourse', 'raith king', 'race king', 'writing'],
}
