hero_aliases = {
    'centaur warrunner': ['Centaur'],
    'dark willow': ['dark will'],
    'disruptor': ['disrupter'],
    'ember spirit': ['Ember'],
    'keeper of the light': ['Keeper'],
    'legion commander': ['Legion'],
    "nature's prophet": ['Furion', 'nature'],
    'pangolier': ['pangolin'],
    'juggernaut': ['Jug'],
    'queen of pain': ['QOP', 'co-op'],
    'storm spirit': ['Storm'],
    'skywrath mage': ['Skywrath'],
    'sven': ['stem', 'spam', 'spend', 'spain'],
    'tidehunter': ['tide hunter'],
    'treant protector': ['Treant'],
    'troll warlord': ['Troll'],
    'vengeful spirit': ['Venge'],
    'windranger': ['Wind Ranger', 'Lyralei'],
}
