hero_aliases = {
    'centaur warrunner': ['Centaur'],
    'disruptor': ['disrupter'],
    'ember spirit': ['Ember'],
    'keeper of the light': ['Keeper'],
    'legion commander': ['Legion'],
    "nature's prophet": ['Furion'],
    'juggernaut': ['Jug'],
    'queen of pain': ['QOP', 'co-op'],
    'storm spirit': ['Storm'],
    'skywrath mage': ['Skywrath'],
    'treant protector': ['Treant'],
    'troll warlord': ['Troll'],
    'vengeful spirit': ['Venge'],
    'windranger': ['Wind Ranger', 'Lyralei'],
}
