# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-14 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hero_advantages', '0002_auto_20171230_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('cooldown', models.SmallIntegerField()),
                ('hotkey', models.CharField(max_length=1)),
                ('is_ultimate', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hero_advantages.Hero')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ability',
            unique_together=set([('hero', 'name')]),
        ),
    ]
