# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_advantages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
