# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-28 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_advantages', '0003_auto_20180125_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='aliases_data',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
