# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advantage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('is_carry', models.BooleanField(default=False)),
                ('is_support', models.BooleanField(default=False)),
                ('is_off_lane', models.BooleanField(default=False)),
                ('is_jungler', models.BooleanField(default=False)),
                ('is_mid', models.BooleanField(default=False)),
                ('is_roaming', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='advantage',
            name='enemy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemy_hero', to='hero_advantages.Hero'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_hero', to='hero_advantages.Hero'),
        ),
        migrations.AlterUniqueTogether(
            name='advantage',
            unique_together=set([('hero', 'enemy')]),
        ),
    ]
